### PR TITLE
Fix spelling mistakes in Command.cs

### PR DESCRIPTION
**Pull request by ArmanMokammel**

### CODE REVIEW

**Review by BaoUida2000 — APPROVED** [review]
wasn't expecting it to come this fast!

**Comment by ArmanMokammel** [comment]
I am actually using this wrapper on my personal server. That's why I had already found those issues yesterday and fixed them on my side which I then decided to create a pull requests for.

**Comment by BaoUida2000** [comment]
don't use the backup feature, it's currently buggy.

**Comment by ArmanMokammel** [comment]
Alright.

**Comment by BaoUida2000** [comment]
idk why but copying files from the list that the server program gives still causes issues, when I load the saved backup, the server tells me that there are miasing files. But ươnly when I do a backup while the server is running using the save hold, save query and save resume command. I still don't know how to fix that and doing online backups right now is very dangerous as it can corrupt your world.

**Comment by ArmanMokammel** [comment]
I see. I will have to conduct some testing on a test server and then I will let you know if I could find a fix for it.

**Comment by BaoUida2000** [comment]
maybe I should open an issue on this.

**Comment by ArmanMokammel** [comment]
Good idea.. we shall then track our progress there.

> maybe I should open an issue on this.

**Pull request merged**
